### Tensorflow

é uma biblioteca de código aberto desenvolvida pela google para realizar cálculos numéricos complexos. Usado em aprendizado de máquina e redes neurais.

O que são Constantes no TensorFlow?

* As constantes são um dos tipos de tensores no TensorFlow que, como o nome sugere, têm valores que não mudam. Elas são usadas para armazenar valores fixos, como hiperparâmetros ou configurações que não se alteram durante a execução do programa.

In [1]:
import tensorflow as tf

# Criar uma constante
constante = tf.constant(3.14, dtype=tf.float32)

print(constante)

tf.Tensor(3.14, shape=(), dtype=float32)


In [8]:
import numpy as np
# Operacoes matematicas básicas com TF
constante1 = tf.constant(4)
constante2 = tf.constant(5)

# Adicao
soma = tf.add(constante1, constante2)
print(f"Soma: {soma}")

# Subtracao
subtracao = tf.subtract(constante1, constante2)
print(f"Subtração: {subtracao}")

# Multipicacao
mult = tf.multiply(constante1, constante2)
print(f"Multiplicação: {mult}")

# Divisão
div = tf.divide(constante1, constante2)
print(f"Divisão: {div}")

Soma: 9
Subtração: -1
Multiplicação: 20
Divisão: 0.8


In [11]:
# Combinacao com variaveis
var = tf.Variable(5)
resultado = constante1 + var
print(resultado)
print(resultado.numpy())

tf.Tensor(9, shape=(), dtype=int32)
9


In [14]:
# Trabalhando com Matrizes
matriz1 = ([1, 2], [3, 4])
matriz2 = ([5, 6], [7, 8])

In [15]:
# Soma de matrizes
soma_matrizes = tf.add(matriz1, matriz2)
print("Soma das Matrizes:\n", soma_matrizes.numpy())

Soma das Matrizes:
 [[ 6  8]
 [10 12]]


In [16]:
# Subtração de matrizes
subtracao_matrizes = tf.subtract(matriz1, matriz2)
print("Subtração das Matrizes:\n", subtracao_matrizes.numpy())

Subtração das Matrizes:
 [[-4 -4]
 [-4 -4]]


In [17]:
# Multiplicacao de matrizes
produto_matriz = tf.matmul(matriz1, matriz2)
print(f"Produto de Matrizes: \n {produto_matriz.numpy()}")

Produto de Matrizes: 
 [[19 22]
 [43 50]]


In [18]:
# Produto de Hadamard
produto_hadamard = tf.multiply(matriz1, matriz2)
print(f"Produto de Hadamard: \n {produto_hadamard.numpy()}")

Produto de Hadamard: 
 [[ 5 12]
 [21 32]]


In [19]:
# Transposicao de matriz
transposta = tf.transpose(matriz1)
print(f"Matriz transposta: \n {transposta.numpy()}")

Matriz transposta: 
 [[1 3]
 [2 4]]


In [29]:
# Determinante
# Definindo uma matriz constante
matrizA = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrizB = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Calculando o determinante
determinante = tf.linalg.det(matrizA)
print("Determinante: ", determinante.numpy())

Determinante:  -2.0


In [30]:
# Inversa (para matrizes nao singulares)
inversa = tf.linalg.inv(matrizA)
print("Inversa da Matriz: \n", inversa.numpy())

Inversa da Matriz: 
 [[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]


In [31]:
# Autovalores e Autovetores
autovalores, autovetores = tf.linalg.eig(tf.cast(matrizA, dtype=tf.complex64))
print("Autovalores: ", autovalores.numpy())
print("Autovetores:\n", autovetores.numpy())

Autovalores:  [-0.37228122+0.j  5.372281  +0.j]
Autovetores:
 [[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]]


In [32]:
# Concatenacao de matrizes
# Concatenação ao longo do eixo 0 (verticalmente)
concat_vertical = tf.concat([matrizA, matrizB], axis=0)
print("Concatenação Vertical:\n", concat_vertical.numpy())

# Concatenação ao longo do eixo 1 (horizontalmente)
concat_horizontal = tf.concat([matrizA, matrizB], axis=1)
print("Concatenação Horizontal:\n", concat_horizontal.numpy())


Concatenação Vertical:
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Concatenação Horizontal:
 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [33]:
# Produto escalar
vetor1 = tf.constant([1, 2, 3], dtype=tf.float32)
vetor2 = tf.constant([4, 5, 6], dtype=tf.float32)

# Calculando o produto escalar
produto_escalar = tf.tensordot(vetor1, vetor2, axes=1)
# axes=1 indica que queremos somar sobre um eixo, que é o comportamento padrão do produto escalar.
print("Produto Escalar:", produto_escalar.numpy())

Produto Escalar: 32.0


In [34]:
# Multiplicação elemento a elemento e depois somando
produto_escalar_alternativo = tf.reduce_sum(vetor1 * vetor2)
print("Produto Escalar (método alternativo):", produto_escalar_alternativo.numpy())
# multiplicamos os vetores elemento a elemento e, em seguida, somamos todos os elementos resultantes para obter o produto escalar.

Produto Escalar (método alternativo): 32.0


um placeholder é uma variável que é usada para alimentar dados para o grafo de computação. Eles são usados para fornecer entradas externas para o grafo. Você pode pensar neles como variáveis que serão preenchidas com dados em um momento posterior. Eles são usados amplamente para permitir que o TensorFlow manipule operações que têm dados de entrada variáveis.

A partir do TensorFlow 2.x, o conceito de placeholders foi substituído pelo uso de funções Python e eager execution, que torna o código mais intuitivo e fácil de depurar. No entanto, se você estiver usando uma versão anterior do TensorFlow (como a 1.x), ainda pode precisar usar placeholders. Aqui está um exemplo básico de como usá-los no TensorFlow 1.x:

In [36]:
import tensorflow as tf

# Função que representa a nossa operação computacional
def my_operation(x):
    return x + 5

# Usando a função com dados concretos
resultado = my_operation(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
print(resultado)

Tensor("add_1:0", shape=(2, 2), dtype=float32)


Os grafos no TensorFlow são estruturas de dados que representam uma série de operações de TensorFlow. Cada nó no grafo representa uma operação, e as arestas representam os Tensores (os dados) que fluem entre estas operações. Esses grafos são uma parte fundamental do TensorFlow e são usados para executar cálculos complexos de forma eficiente.

O TensorBoard é uma ferramenta de visualização fornecida pelo TensorFlow para entender, depurar e otimizar modelos de aprendizado de máquina. Ele oferece visualizações gráficas dos grafos de computação, além de outras funcionalidades como acompanhamento de métricas, visualização de imagens, histogramas de parâmetros e muito mais.

In [37]:
import tensorflow as tf

# Criação de um grafo simples
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
c = tf.add(a, b, name="soma")

print(c)


Tensor("soma:0", shape=(), dtype=int32)


In [39]:
# Escrever logs para TensorBoard
logdir = "logs/exemplo_simples/"
writer = tf.summary.create_file_writer(logdir)

# Iniciando a gravação dos logs
tf.summary.trace_on(graph=True, profiler=True)

# Executando o grafo
with writer.as_default():
    tf.summary.trace_export(name="exemplo_simples", step=0, profiler_outdir=logdir)
